// <auto-generated />
using Classroom.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable
namespace Classroom.Storage.Migrations
{
    [DbContext(typeof(ClassroomDb))]
    partial class ClassroomDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");
            modelBuilder.Entity("Classroom.Storage.AssignmentEntity", b =>
            {
                b.Property<string>("StudentId").HasColumnType("TEXT");
                b.Property<string>("TaskId").HasColumnType("TEXT");
                b.Property<int>("ActiveSeconds").HasColumnType("INTEGER");
                b.Property<int>("Checks").HasColumnType("INTEGER");
                b.Property<long?>("CompletedAt").HasColumnType("INTEGER");
                b.Property<string>("Draft").IsRequired().HasColumnType("TEXT");
                b.Property<int>("Errors").HasColumnType("INTEGER");
                b.Property<string>("HintsJson").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Json").IsRequired().HasColumnType("TEXT");
                b.Property<int>("ProjectOrder").HasColumnType("INTEGER");
                b.Property<int>("Revision").HasColumnType("INTEGER");
                b.HasKey("StudentId", "TaskId");
                b.ToTable("Assignments");
            });
            modelBuilder.Entity("Classroom.Storage.AttemptEntity", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<long>("At").HasColumnType("INTEGER");
                b.Property<string>("Kind").IsRequired().HasColumnType("TEXT");
                b.Property<string>("StudentId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("TaskId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("StudentId");
                b.ToTable("Attempts");
            });
            modelBuilder.Entity("Classroom.Storage.GroupEntity", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Groups");
            });
            modelBuilder.Entity("Classroom.Storage.ImportEntity", b =>
            {
                b.Property<string>("Hash").HasColumnType("TEXT");
                b.Property<long>("At").HasColumnType("INTEGER");
                b.HasKey("Hash");
                b.ToTable("Imports");
            });
            modelBuilder.Entity("Classroom.Storage.OperationEntity", b =>
            {
                b.Property<string>("StudentId").HasColumnType("TEXT");
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<long>("At").HasColumnType("INTEGER");
                b.Property<string>("RequestHash").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ResponseJson").IsRequired().HasColumnType("TEXT");
                b.HasKey("StudentId", "Id");
                b.ToTable("Operations");
            });
            modelBuilder.Entity("Classroom.Storage.ProfileEntity", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("GroupId").HasColumnType("TEXT");
                b.Property<long>("LockedUntil").HasColumnType("INTEGER");
                b.Property<string>("Login").IsRequired().HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                b.Property<string>("PresetsJson").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Role").IsRequired().HasColumnType("TEXT");
                b.Property<int>("Slot").HasColumnType("INTEGER");
                b.Property<string>("ThemeJson").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("GroupId");
                b.HasIndex("Login").IsUnique();
                b.ToTable("Profiles");
            });
            modelBuilder.Entity("Classroom.Storage.SnapshotEntity", b =>
            {
                b.Property<string>("StudentId").HasColumnType("TEXT");
                b.Property<string>("Project").HasColumnType("TEXT");
                b.Property<string>("Base64").IsRequired().HasColumnType("TEXT");
                b.HasKey("StudentId", "Project");
                b.ToTable("Snapshots");
            });
            modelBuilder.Entity("Classroom.Storage.TaskEntity", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<bool>("Deleted").HasColumnType("INTEGER");
                b.Property<string>("Json").IsRequired().HasColumnType("TEXT");
                b.Property<bool>("Restricted").HasColumnType("INTEGER");
                b.Property<int>("Revision").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.ToTable("Tasks");
            });
            modelBuilder.Entity("Classroom.Storage.TaskRevisionEntity", b =>
            {
                b.Property<string>("TaskId").HasColumnType("TEXT");
                b.Property<int>("Revision").HasColumnType("INTEGER");
                b.Property<string>("AlternativesJson").IsRequired().HasColumnType("TEXT");
                b.Property<long>("At").HasColumnType("INTEGER");
                b.Property<bool>("Deleted").HasColumnType("INTEGER");
                b.Property<string>("Json").IsRequired().HasColumnType("TEXT");
                b.Property<bool>("Restricted").HasColumnType("INTEGER");
                b.HasKey("TaskId", "Revision");
                b.ToTable("TaskRevisions");
            });
            modelBuilder.Entity("Classroom.Storage.VariantEntity", b =>
            {
                b.Property<string>("TaskId").HasColumnType("TEXT");
                b.Property<int>("Index").HasColumnType("INTEGER");
                b.Property<string>("Json").IsRequired().HasColumnType("TEXT");
                b.HasKey("TaskId", "Index");
                b.ToTable("Variants");
            });
            modelBuilder.Entity("Classroom.Storage.AssignmentEntity", b =>
            {
                b.HasOne("Classroom.Storage.ProfileEntity", null).WithMany().HasForeignKey("StudentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("Classroom.Storage.AttemptEntity", b =>
            {
                b.HasOne("Classroom.Storage.ProfileEntity", null).WithMany().HasForeignKey("StudentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("Classroom.Storage.OperationEntity", b =>
            {
                b.HasOne("Classroom.Storage.ProfileEntity", null).WithMany().HasForeignKey("StudentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("Classroom.Storage.ProfileEntity", b =>
            {
                b.HasOne("Classroom.Storage.GroupEntity", null).WithMany().HasForeignKey("GroupId").OnDelete(DeleteBehavior.Restrict);
            });
            modelBuilder.Entity("Classroom.Storage.SnapshotEntity", b =>
            {
                b.HasOne("Classroom.Storage.ProfileEntity", null).WithMany().HasForeignKey("StudentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("Classroom.Storage.TaskRevisionEntity", b =>
            {
                b.HasOne("Classroom.Storage.TaskEntity", null).WithMany().HasForeignKey("TaskId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("Classroom.Storage.VariantEntity", b =>
            {
                b.HasOne("Classroom.Storage.TaskEntity", null).WithMany().HasForeignKey("TaskId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
