import { teacherTasks } from "./teacher-tasks";
import { teacherExtraTasks } from "./teacher-extra-tasks";
import { teacherCaseTasks } from "./teacher-case-tasks";
import { parkingFullTasks } from "./parking-full-tasks";

export type Task = {
  id: string;
  module: string;
  title: string;
  minutes: number;
  concept: string;
  terms: string[];
  example: string;
  prompt: string;
  starter: string;
  solution: string;
  hints: [string, string];
  seed: string;
  seedProfile?: "parking-spots" | "parking-database" | "case-sx4" | "sugar-success" | "globus-budget";
  mode?: "query" | "state";
  ordered?: boolean;
  project?: string;
  variantEligible?: boolean;
  variantIndex?: number;
  tableMap?: Record<string, string>;
  dataVariant?: number;
};

const people = `CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT NOT NULL, city TEXT, age INTEGER);
INSERT INTO students VALUES (1,'Аня','Москва',19),(2,'Борис','Казань',22),(3,'Вика','Москва',21),(4,'Глеб','Тула',18);`;
const orders = `${people}
CREATE TABLE orders (id INTEGER PRIMARY KEY, student_id INTEGER, amount INTEGER, status TEXT);
INSERT INTO orders VALUES (1,1,1200,'paid'),(2,2,800,'new'),(3,1,400,'paid'),(4,3,1700,'new');`;
const variantOrders = `${orders}
INSERT INTO orders VALUES (5,1,320,'new'),(6,2,550,'paid'),(7,3,770,'new'),(8,4,990,'paid'),(9,2,1210,'new'),(10,3,1430,'paid'),(11,4,1650,'new'),(12,1,1870,'paid');`;

export const lessons: Task[] = [
  { id:"database",module:"01 · Старт",title:"База, таблица, строка",minutes:3,concept:"База данных хранит таблицы. Таблица похожа на список: столбцы описывают свойства, строки — отдельные записи. SQL — язык, на котором мы задаём базе вопросы.",terms:["база данных","таблица","строка","столбец"],example:"SELECT * FROM students;",prompt:"Покажи все строки и все столбцы таблицы students.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT * FROM students;",hints:["SELECT выбирает данные из таблицы.","Звёздочка означает все столбцы: SELECT * FROM students;"],seed:people,variantEligible:false},
  { id:"columns",module:"01 · Старт",title:"Выбираем столбцы",minutes:3,concept:"Не обязательно выводить всё. После SELECT перечисли нужные столбцы через запятую.",terms:["SELECT","FROM"],example:"SELECT name FROM students;",prompt:"Покажи имена и города учеников. В ответе должны быть только столбцы name и city.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT name, city FROM students;",hints:["Нужные столбцы: name и city.","Напиши SELECT name, city FROM students;"],seed:people,variantEligible:false},
  { id:"where",module:"02 · Поиск",title:"Фильтр WHERE",minutes:4,concept:"WHERE оставляет только строки, подходящие под условие. Текстовое значение пишется в одинарных кавычках.",terms:["WHERE","условие"],example:"SELECT name FROM students WHERE age > 20;",prompt:"Выведи name и age учеников из Москвы.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT name, age FROM students WHERE city = 'Москва';",hints:["Сравни значение столбца city с текстом Москва.","Условие: WHERE city = 'Москва'."],seed:people},
  { id:"sort",module:"02 · Поиск",title:"Сортировка и LIMIT",minutes:4,concept:"ORDER BY задаёт порядок. DESC — от большего к меньшему, LIMIT ограничивает число строк.",terms:["ORDER BY","DESC","LIMIT"],example:"SELECT * FROM students ORDER BY age DESC;",prompt:"Покажи имя и возраст двух самых старших учеников, от старшего к младшему.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT name, age FROM students ORDER BY age DESC LIMIT 2;",hints:["Сначала отсортируй по age по убыванию.","Добавь ORDER BY age DESC LIMIT 2."],seed:people,ordered:true},
  { id:"aggregate",module:"03 · Анализ",title:"Считаем строки",minutes:4,concept:"Функции COUNT, SUM и AVG сворачивают несколько строк в одно число. COUNT(*) считает строки.",terms:["COUNT","агрегат"],example:"SELECT COUNT(*) FROM students;",prompt:"Посчитай количество заказов и назови столбец total.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT COUNT(*) AS total FROM orders;",hints:["Используй COUNT(*).","Дай результату имя: COUNT(*) AS total."],seed:orders},
  { id:"group",module:"03 · Анализ",title:"Группировка",minutes:5,concept:"GROUP BY собирает строки с одинаковым значением. Так можно считать итог отдельно для каждой группы.",terms:["GROUP BY","SUM"],example:"SELECT city, COUNT(*) FROM students GROUP BY city;",prompt:"Покажи status и общую сумму amount для каждого статуса заказа. Сумму назови total.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT status, SUM(amount) AS total FROM orders GROUP BY status;",hints:["Сгруппируй по status.","Используй SUM(amount) AS total и GROUP BY status."],seed:orders},
  { id:"join",module:"04 · Связи",title:"Соединяем таблицы",minutes:6,concept:"JOIN связывает строки разных таблиц по ключам. orders.student_id указывает на students.id.",terms:["JOIN","первичный ключ","внешний ключ"],example:"SELECT students.name, orders.amount FROM students JOIN orders ON students.id = orders.student_id;",prompt:"Покажи имя ученика и сумму каждого заказа. Столбцы назови name и amount.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT students.name, orders.amount FROM students JOIN orders ON students.id = orders.student_id;",hints:["Связь идёт через students.id и orders.student_id.","После ON напиши students.id = orders.student_id."],seed:orders},
  { id:"subquery",module:"04 · Связи",title:"Вложенный запрос",minutes:6,concept:"Подзапрос — запрос внутри другого. Он помогает сначала вычислить значение, а затем сравнить с ним строки.",terms:["подзапрос","AVG"],example:"SELECT name FROM students WHERE age > (SELECT AVG(age) FROM students);",prompt:"Покажи name учеников старше среднего возраста.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT name FROM students WHERE age > (SELECT AVG(age) FROM students);",hints:["Внутренний запрос должен вычислить средний age.","Используй SELECT AVG(age) FROM students."],seed:people},
  { id:"create",module:"05 · Своя база",title:"Создаём таблицу",minutes:6,concept:"CREATE TABLE задаёт имя таблицы и её столбцы. PRIMARY KEY отличает одну запись от другой; NOT NULL запрещает пустое значение.",terms:["CREATE TABLE","INTEGER","TEXT","PRIMARY KEY","NOT NULL"],example:"CREATE TABLE books (id INTEGER PRIMARY KEY, title TEXT NOT NULL);",prompt:"Создай таблицу books с id INTEGER PRIMARY KEY и title TEXT NOT NULL.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"CREATE TABLE books (id INTEGER PRIMARY KEY, title TEXT NOT NULL);",hints:["Описания столбцов разделяются запятой.","CREATE TABLE books (id INTEGER PRIMARY KEY, title TEXT NOT NULL);"],seed:"",mode:"state"},
  { id:"insert",module:"05 · Своя база",title:"Добавляем запись",minutes:4,concept:"INSERT INTO добавляет новую строку. Явно перечисляй столбцы, чтобы порядок значений не стал ловушкой.",terms:["INSERT INTO","VALUES"],example:"INSERT INTO books (id,title) VALUES (1,'Мастер и Маргарита');",prompt:"Добавь книгу с id 2 и названием 'Дюна'.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"INSERT INTO books (id,title) VALUES (2,'Дюна');",hints:["Нужна команда INSERT INTO books.","Укажи (id,title) VALUES (2,'Дюна')."],seed:"CREATE TABLE books (id INTEGER PRIMARY KEY, title TEXT NOT NULL); INSERT INTO books VALUES (1,'1984');",mode:"state"},
  { id:"update",module:"06 · Изменения",title:"Обновляем строки",minutes:5,concept:"UPDATE меняет существующие строки. WHERE выбирает, какие именно. Без WHERE изменятся все строки — перед запуском проверь условие.",terms:["UPDATE","SET"],example:"UPDATE books SET title='Новое имя' WHERE id=1;",prompt:"Измени status заказа с id 2 на 'paid'. Остальные заказы оставь как есть.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"UPDATE orders SET status='paid' WHERE id=2;",hints:["Используй UPDATE orders SET status = 'paid'.","Добавь WHERE id = 2, чтобы не затронуть другие заказы."],seed:orders,mode:"state"},
  { id:"delete",module:"06 · Изменения",title:"Удаляем строку",minutes:4,concept:"DELETE удаляет строки. Условие WHERE особенно важно: без него исчезнут все записи таблицы.",terms:["DELETE","WHERE"],example:"DELETE FROM orders WHERE id=4;",prompt:"Удали только заказ с id 4.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"DELETE FROM orders WHERE id=4;",hints:["Команда начинается с DELETE FROM orders.","Условие — WHERE id = 4."],seed:orders,mode:"state"},
  { id:"constraint",module:"07 · Надёжность",title:"Ограничения данных",minutes:6,concept:"Ограничения защищают таблицу от неверных данных. UNIQUE запрещает повторы, CHECK проверяет условие, FOREIGN KEY связывает таблицы.",terms:["UNIQUE","CHECK","FOREIGN KEY"],example:"CREATE TABLE tags (name TEXT UNIQUE NOT NULL);",prompt:"Создай таблицу tickets: id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, price INTEGER CHECK(price >= 0).",starter:"-- Напиши SQL-запрос по заданию выше",solution:"CREATE TABLE tickets (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, price INTEGER CHECK(price >= 0));",hints:["Для code нужны NOT NULL и UNIQUE.","Для price используй CHECK(price >= 0)."],seed:"",mode:"state"},
  { id:"transaction",module:"07 · Надёжность",title:"Транзакции",minutes:6,concept:"Транзакция объединяет изменения: либо выполняются все, либо откатываются. BEGIN начинает её, COMMIT сохраняет, ROLLBACK отменяет.",terms:["BEGIN","COMMIT","ROLLBACK"],example:"BEGIN; UPDATE accounts SET balance=balance-100 WHERE id=1; COMMIT;",prompt:"Переведи 100 единиц со счёта 1 на счёт 2 в одной транзакции.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"BEGIN; UPDATE accounts SET balance=balance-100 WHERE id=1; UPDATE accounts SET balance=balance+100 WHERE id=2; COMMIT;",hints:["Один UPDATE уменьшает счёт 1, второй увеличивает счёт 2.","Оберни оба UPDATE в BEGIN и COMMIT."],seed:"CREATE TABLE accounts (id INTEGER PRIMARY KEY,balance INTEGER); INSERT INTO accounts VALUES (1,500),(2,200);",mode:"state"},
  { id:"index",module:"08 · Развитие базы",title:"Индексы",minutes:5,concept:"Индекс ускоряет поиск по столбцу, но занимает место и замедляет запись. Создавай его для часто используемых условий.",terms:["CREATE INDEX","индекс"],example:"CREATE INDEX idx_students_city ON students(city);",prompt:"Создай индекс idx_students_city для столбца city таблицы students.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"CREATE INDEX idx_students_city ON students(city);",hints:["Нужна команда CREATE INDEX.","Напиши CREATE INDEX idx_students_city ON students(city);"],seed:people,mode:"state"},
  { id:"alter",module:"08 · Развитие базы",title:"Меняем структуру",minutes:5,concept:"ALTER TABLE меняет уже созданную таблицу. При добавлении столбца старые строки сохраняются; новый столбец в них обычно получает NULL или значение по умолчанию.",terms:["ALTER TABLE","ADD COLUMN","миграция"],example:"ALTER TABLE students ADD COLUMN email TEXT;",prompt:"Добавь в таблицу students столбец email типа TEXT.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"ALTER TABLE students ADD COLUMN email TEXT;",hints:["Начни с ALTER TABLE students.","Добавь ADD COLUMN email TEXT."],seed:people,mode:"state"},
];

const library = "CREATE TABLE books (id INTEGER PRIMARY KEY,title TEXT NOT NULL,author TEXT NOT NULL); INSERT INTO books VALUES (1,'Дюна','Фрэнк Герберт'),(2,'1984','Джордж Оруэлл');";
const shop = "CREATE TABLE products (id INTEGER PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL); INSERT INTO products VALUES (1,'Чай',200),(2,'Кофе',350);";
const classes = "CREATE TABLE courses (id INTEGER PRIMARY KEY,title TEXT NOT NULL); INSERT INTO courses VALUES (1,'SQL'),(2,'Python');";

export const projects: Task[] = [
  {id:"lib1",project:"library",module:"Проект · Библиотека",title:"Читатели",minutes:6,concept:"Создай таблицу читателей, чтобы библиотека могла хранить их имена.",terms:["CREATE TABLE","PRIMARY KEY"],example:"CREATE TABLE books (...);",prompt:"Создай readers с id INTEGER PRIMARY KEY и name TEXT NOT NULL.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"CREATE TABLE readers (id INTEGER PRIMARY KEY,name TEXT NOT NULL);",hints:["Таблица называется readers.","CREATE TABLE readers (id INTEGER PRIMARY KEY,name TEXT NOT NULL);"],seed:library,mode:"state"},
  {id:"lib2",project:"library",module:"Проект · Библиотека",title:"Новый читатель",minutes:4,concept:"Теперь в созданную таблицу нужно добавить первого читателя.",terms:["INSERT INTO"],example:"INSERT INTO books VALUES (3,'Книга','Автор');",prompt:"Добавь в readers запись (1, 'Аня').",starter:"-- Напиши SQL-запрос по заданию выше",solution:"INSERT INTO readers (id,name) VALUES (1,'Аня');",hints:["Используй INSERT INTO readers.","Значения: (1,'Аня')."],seed:library,mode:"state"},
  {id:"lib3",project:"library",module:"Проект · Библиотека",title:"Выдача книг",minutes:7,concept:"Таблица выдач соединит книги и читателей через их идентификаторы.",terms:["FOREIGN KEY"],example:"reader_id INTEGER REFERENCES readers(id)",prompt:"Создай loans: id INTEGER PRIMARY KEY, book_id INTEGER REFERENCES books(id), reader_id INTEGER REFERENCES readers(id).",starter:"-- Напиши SQL-запрос по заданию выше",solution:"CREATE TABLE loans (id INTEGER PRIMARY KEY,book_id INTEGER REFERENCES books(id),reader_id INTEGER REFERENCES readers(id));",hints:["Нужны столбцы book_id и reader_id.","Для каждого укажи REFERENCES на нужную таблицу."],seed:library,mode:"state"},
  {id:"lib4",project:"library",module:"Проект · Библиотека",title:"Отчёт по книгам",minutes:6,concept:"Заверши проект запросом к созданной базе.",terms:["SELECT","ORDER BY"],example:"SELECT title FROM books;",prompt:"Покажи title и author книг в порядке названий.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT title, author FROM books ORDER BY title;",hints:["Выбери два столбца из books.","Добавь ORDER BY title."],seed:library,ordered:true},
  {id:"shop1",project:"shop",module:"Проект · Магазин",title:"Учёт заказов",minutes:7,concept:"Магазину нужна отдельная таблица заказов, связанная с товарами.",terms:["CREATE TABLE","REFERENCES"],example:"product_id INTEGER REFERENCES products(id)",prompt:"Создай purchases: id INTEGER PRIMARY KEY, product_id INTEGER REFERENCES products(id), quantity INTEGER NOT NULL.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"CREATE TABLE purchases (id INTEGER PRIMARY KEY,product_id INTEGER REFERENCES products(id),quantity INTEGER NOT NULL);",hints:["Создай таблицу purchases.","Добавь ссылку product_id на products(id)."],seed:shop,mode:"state"},
  {id:"shop2",project:"shop",module:"Проект · Магазин",title:"Первая покупка",minutes:4,concept:"Запишем заказ на два чая.",terms:["INSERT INTO"],example:"INSERT INTO purchases VALUES (1,1,2);",prompt:"Добавь в purchases заказ id 1, product_id 1, quantity 2.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"INSERT INTO purchases VALUES (1,1,2);",hints:["Используй INSERT INTO purchases.","Значения: 1, 1, 2."],seed:shop,mode:"state"},
  {id:"shop3",project:"shop",module:"Проект · Магазин",title:"Изменение цены",minutes:5,concept:"Цена товара может меняться без изменения старых идентификаторов.",terms:["UPDATE"],example:"UPDATE products SET price=250 WHERE id=1;",prompt:"Установи цену чая (id 1) равной 250.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"UPDATE products SET price=250 WHERE id=1;",hints:["Обнови таблицу products.","Используй WHERE id=1."],seed:shop,mode:"state"},
  {id:"shop4",project:"shop",module:"Проект · Магазин",title:"Выручка",minutes:6,concept:"JOIN и SUM вместе позволяют посчитать стоимость заказов.",terms:["JOIN","SUM"],example:"SELECT SUM(price * quantity) FROM products JOIN purchases ON products.id=purchases.product_id;",prompt:"Посчитай общую стоимость заказов. Назови столбец revenue.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"SELECT SUM(products.price * purchases.quantity) AS revenue FROM products JOIN purchases ON products.id=purchases.product_id;",hints:["Умножь price на quantity.","Суммируй результат с SUM и назови revenue."],seed:shop},
  {id:"class1",project:"classes",module:"Проект · Запись на занятия",title:"Список учеников",minutes:6,concept:"Создай таблицу для учеников учебного центра.",terms:["CREATE TABLE"],example:"CREATE TABLE courses (...);",prompt:"Создай learners: id INTEGER PRIMARY KEY, name TEXT NOT NULL.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"CREATE TABLE learners (id INTEGER PRIMARY KEY,name TEXT NOT NULL);",hints:["Таблица называется learners.","В ней нужны id и name."],seed:classes,mode:"state"},
  {id:"class2",project:"classes",module:"Проект · Запись на занятия",title:"Записи на курс",minutes:7,concept:"Связующая таблица позволит одному ученику записаться на несколько курсов.",terms:["внешний ключ"],example:"course_id INTEGER REFERENCES courses(id)",prompt:"Создай enrollments: id INTEGER PRIMARY KEY, learner_id INTEGER REFERENCES learners(id), course_id INTEGER REFERENCES courses(id).",starter:"-- Напиши SQL-запрос по заданию выше",solution:"CREATE TABLE enrollments (id INTEGER PRIMARY KEY,learner_id INTEGER REFERENCES learners(id),course_id INTEGER REFERENCES courses(id));",hints:["Нужны два внешних ключа.","Один ссылается на learners(id), второй на courses(id)."],seed:classes,mode:"state"},
  {id:"class3",project:"classes",module:"Проект · Запись на занятия",title:"Новый курс",minutes:4,concept:"Расширим каталог занятий.",terms:["INSERT INTO"],example:"INSERT INTO courses VALUES (3,'Дизайн');",prompt:"Добавь курс с id 3 и названием 'Аналитика'.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"INSERT INTO courses VALUES (3,'Аналитика');",hints:["Добавляй строку в courses.","Значения: 3 и 'Аналитика'."],seed:classes,mode:"state"},
  {id:"class4",project:"classes",module:"Проект · Запись на занятия",title:"Обновление схемы",minutes:6,concept:"Продукт развивается: курсу теперь нужно описание. Старые записи должны сохраниться.",terms:["ALTER TABLE","ADD COLUMN"],example:"ALTER TABLE courses ADD COLUMN description TEXT;",prompt:"Добавь в courses столбец description типа TEXT.",starter:"-- Напиши SQL-запрос по заданию выше",solution:"ALTER TABLE courses ADD COLUMN description TEXT;",hints:["Используй ALTER TABLE courses.","Добавь ADD COLUMN description TEXT."],seed:classes,mode:"state"},
];

export const randomizedOrderTask: Task = {
  id:"random-orders",module:"02 · Поиск",title:"Персональный вариант · заказы",minutes:5,
  concept:"У каждого ученика свой случайный вариант: меняются статус, порог суммы и порядок сортировки.",
  terms:["WHERE","AND","ORDER BY"],example:"SELECT id, amount FROM orders WHERE status = 'new' AND amount > 500 ORDER BY amount DESC;",
  prompt:"Покажи id и amount заказов со статусом 'new' и суммой больше 500. Отсортируй по amount по убыванию.",starter:"-- Напиши SQL-запрос по заданию выше",
  solution:"SELECT id, amount FROM orders WHERE status = 'new' AND amount > 500 ORDER BY amount DESC;",
  hints:["Отфильтруй status = 'new' и amount > 500.","Добавь ORDER BY amount DESC."],seed:variantOrders,ordered:true
};

export const allTasks = [...lessons, randomizedOrderTask, ...projects, ...teacherTasks, ...teacherExtraTasks, ...teacherCaseTasks, ...parkingFullTasks];
export const glossary: Record<string,string> = {
  "база данных":"Набор связанных таблиц и других объектов, с которыми работает СУБД.","таблица":"Данные в виде строк и столбцов.","строка":"Одна запись в таблице, например один ученик.","столбец":"Свойство записи, например name или age.","SELECT":"Команда чтения данных.","FROM":"Указывает таблицу, откуда читаем данные.","WHERE":"Условие отбора строк.","условие":"Проверка, по которой остаются нужные строки.","ORDER BY":"Сортирует результат.","DESC":"Сортировка по убыванию.","LIMIT":"Ограничивает число строк результата.","COUNT":"Считает строки или значения.","агрегат":"Функция, сворачивающая несколько строк в один итог.","GROUP BY":"Объединяет строки в группы для расчёта итогов.","SUM":"Складывает числовые значения.","JOIN":"Соединяет строки разных таблиц.","первичный ключ":"Уникальный идентификатор строки.","внешний ключ":"Значение, указывающее на строку другой таблицы.","подзапрос":"SQL-запрос внутри другого запроса.","AVG":"Вычисляет среднее арифметическое.","CREATE TABLE":"Создаёт таблицу.","INTEGER":"Целое число.","TEXT":"Текстовое значение.","PRIMARY KEY":"Объявляет первичный ключ.","NOT NULL":"Запрещает пустое значение NULL.","INSERT INTO":"Добавляет строки в таблицу.","VALUES":"Перечисляет добавляемые значения.","UPDATE":"Обновляет существующие строки.","SET":"Указывает новые значения столбцов.","DELETE":"Удаляет строки из таблицы.","UNIQUE":"Запрещает повторяющиеся значения.","CHECK":"Проверяет условие для данных.","FOREIGN KEY":"Задаёт связь с другой таблицей.","BEGIN":"Начинает транзакцию.","COMMIT":"Сохраняет изменения транзакции.","ROLLBACK":"Отменяет изменения транзакции.","CREATE INDEX":"Создаёт индекс для ускорения поиска.","индекс":"Вспомогательная структура, ускоряющая поиск.","ALTER TABLE":"Меняет структуру таблицы.","ADD COLUMN":"Добавляет новый столбец.","миграция":"Контролируемое изменение структуры базы."};

export const glossaryLong: Record<string,string> = {
  "база данных":"База данных — организованное хранилище. В SQLite это файл или учебная база в памяти; внутри находятся таблицы, индексы и правила связей. Сначала продумай, какие сущности нужно хранить, и раздели их на таблицы.",
  "таблица":"Таблица хранит записи одного типа: например, только учеников или только заказы. Столбцы задают свойства, а каждая строка — отдельный экземпляр. Таблицы связываются ключами, чтобы не копировать одни и те же сведения.",
  "строка":"Строка — одна запись: например, один ученик с именем, городом и возрастом. Каждая строка должна отличаться от других; обычно для этого используют первичный ключ.",
  "столбец":"Столбец — одно свойство всех записей таблицы: имя, цена или дата. У столбца есть имя и тип данных. При создании таблицы полезно сразу решить, может ли значение быть пустым и должно ли оно быть уникальным.",
  "SELECT":"SELECT читает данные и возвращает результат, не меняя исходные записи. После SELECT перечисляют столбцы, затем FROM с таблицей; WHERE, GROUP BY и ORDER BY добавляют по необходимости.",
  "FROM":"FROM указывает источник строк для SELECT. Обычно это таблица, но можно читать из JOIN или подзапроса. Если нужной таблицы нет в FROM или JOIN, её столбцы недоступны запросу.",
  "WHERE":"WHERE фильтрует строки до группировки: в результате остаются только записи, для которых условие истинно. Текст сравнивают в одинарных кавычках, например city = 'Москва'. Для нескольких условий используют AND и OR.",
  "условие":"Условие — проверка, которая для каждой строки даёт «да» или «нет». Примеры: age >= 18, city = 'Тула'. В WHERE условие отбирает строки, а в CHECK защищает таблицу от недопустимых значений.",
  "ORDER BY":"ORDER BY сортирует итоговые строки по одному или нескольким столбцам. По умолчанию порядок возрастающий; DESC задаёт убывание. Чтобы результат был стабильным при равных значениях, добавь второй критерий сортировки.",
  "DESC":"DESC означает убывающий порядок: от большего к меньшему или от новых дат к старым. Его ставят после столбца сортировки в ORDER BY. Противоположное направление — ASC.",
  "LIMIT":"LIMIT оставляет только первые N строк результата. Часто его используют вместе с ORDER BY, чтобы найти, например, три самых дорогих товара. Без сортировки «первые» строки не означают конкретный порядок.",
  "COUNT":"COUNT(*) считает строки, а COUNT(column) считает только непустые значения этого столбца. Чтобы результат было проще читать, задай псевдоним через AS, например COUNT(*) AS total.",
  "агрегат":"Агрегатная функция сводит множество значений к одному итогу: COUNT считает, SUM складывает, AVG находит среднее, MIN и MAX ищут крайние значения. С GROUP BY итог можно получить отдельно для каждой группы.",
  "GROUP BY":"GROUP BY объединяет строки с одинаковым значением, например все заказы одного статуса. Для каждой группы обычно считают агрегат. Каждый выбранный столбец должен быть сгруппирован или передан агрегатной функции.",
  "SUM":"SUM складывает числовые значения столбца. Пустые значения NULL пропускаются; если складывать нечего, результат может быть NULL. Сочетай SUM с GROUP BY для суммы по категориям.",
  "JOIN":"JOIN соединяет строки из таблиц по условию ON. Чаще всего первичный ключ одной таблицы сравнивают с внешним ключом другой. Если совпадения нет, обычный JOIN не включает строку; LEFT JOIN сохраняет все строки слева.",
  "первичный ключ":"Первичный ключ (PRIMARY KEY) однозначно находит строку. Он не повторяется и не бывает NULL. Обычно это короткий id, который удобно использовать в связях с другими таблицами.",
  "внешний ключ":"Внешний ключ хранит ссылку на существующую строку другой таблицы, например orders.student_id → students.id. Он защищает связи от ссылок на несуществующие записи. В SQLite проверка внешних ключей должна быть включена.",
  "подзапрос":"Подзапрос — запрос, вложенный в другой SQL-запрос. Его результат может стать таблицей, списком значений или одним числом. Используй его, когда сначала нужно что-то вычислить, а потом отфильтровать внешний запрос.",
  "AVG":"AVG вычисляет среднее арифметическое числовых значений, пропуская NULL. Среднее может быть дробным. Например, сравнить возраст каждого ученика со средним можно через подзапрос SELECT AVG(age) ... .",
  "CREATE TABLE":"CREATE TABLE создаёт новую таблицу и её структуру. В скобках перечисляют столбцы, типы и ограничения. До запуска проверь, не существует ли уже таблица с таким именем; для безопасного повторного запуска есть IF NOT EXISTS.",
  "INTEGER":"INTEGER — тип целых чисел: например, количество или идентификатор. В SQLite типы допускают гибкость, но выбирай тип по смыслу данных. Денежные суммы для точности часто хранят целым числом копеек.",
  "TEXT":"TEXT хранит текст: имя, название или комментарий. Строковые значения в SQL заключают в одинарные кавычки. Имя столбца обычно пишут без кавычек.",
  "PRIMARY KEY":"PRIMARY KEY объявляет столбец или набор столбцов первичным ключом таблицы. Ключ уникален и не допускает NULL; INTEGER PRIMARY KEY в SQLite связан с внутренним идентификатором строки.",
  "NOT NULL":"NOT NULL запрещает оставлять столбец пустым. При INSERT нужно передать значение либо настроить значение по умолчанию. Это полезно для обязательных данных, например названия товара.",
  "INSERT INTO":"INSERT INTO добавляет новые строки в таблицу. Укажи список столбцов, а затем VALUES в том же порядке. Явный список столбцов делает запрос понятнее и устойчивее к изменению таблицы.",
  "VALUES":"VALUES задаёт значения для новой строки после INSERT INTO. Позиции значений соответствуют указанным столбцам. Текст заключают в одинарные кавычки, числа — нет; NULL обозначает отсутствие значения.",
  "UPDATE":"UPDATE меняет существующие строки. SET задаёт новые значения, а WHERE ограничивает изменение нужными записями. Перед запуском полезно выполнить SELECT с тем же условием, чтобы увидеть затронутые строки.",
  "SET":"SET перечисляет изменения столбцов в UPDATE: например SET price = 250. Несколько присваиваний разделяют запятыми. Без WHERE обычно обновятся все строки таблицы.",
  "DELETE":"DELETE удаляет строки из таблицы. WHERE выбирает записи для удаления; без WHERE удалятся все строки, но сама таблица останется. Перед удалением проверь условие запросом SELECT.",
  "UNIQUE":"UNIQUE запрещает повтор значений в столбце или комбинации столбцов. Это подходит для электронной почты или кода товара. NULL в SQLite имеет особое поведение и может встречаться несколько раз.",
  "CHECK":"CHECK задаёт правило допустимости строки, например price >= 0. Если новая или изменённая запись нарушит проверку, SQLite отменит операцию и покажет ошибку ограничения.",
  "FOREIGN KEY":"FOREIGN KEY объявляет столбец-ссылку на ключ другой таблицы. Он помогает сохранять корректные отношения, например заказ не может указывать на несуществующего ученика. Удаление родительской строки может быть запрещено, если на неё ссылаются.",
  "BEGIN":"BEGIN начинает транзакцию — группу изменений, которая пока не считается окончательно сохранённой. Можно выполнить несколько шагов, проверить итог и затем подтвердить или отменить их.",
  "COMMIT":"COMMIT подтверждает изменения открытой транзакции. После фиксации они становятся постоянными в базе. Если передумал до COMMIT, можно выполнить ROLLBACK.",
  "ROLLBACK":"ROLLBACK отменяет изменения с начала текущей транзакции, если они ещё не зафиксированы через COMMIT. Это защита от частично выполненной операции и ошибок в серии изменений.",
  "CREATE INDEX":"CREATE INDEX создаёт дополнительную структуру для более быстрого поиска и соединения по столбцам. Индекс занимает место и замедляет изменение строк, поэтому индексируй поля, по которым база действительно часто ищет.",
  "индекс":"Индекс похож на алфавитный указатель: он помогает быстрее находить строки по выбранному столбцу. Он не меняет сами данные, но требует места и обновляется при INSERT, UPDATE и DELETE.",
  "ALTER TABLE":"ALTER TABLE меняет структуру уже существующей таблицы: например, добавляет столбец или переименовывает объект. Возможности зависят от диалекта базы. Перед изменением важно понять, что станет со старыми строками.",
  "ADD COLUMN":"ADD COLUMN добавляет новый столбец в существующую таблицу. Старые строки получают NULL либо значение DEFAULT. Если новый столбец обязателен, задай подходящее значение по умолчанию или сначала продумай заполнение старых записей.",
  "миграция":"Миграция — записанное и упорядоченное изменение схемы базы. Она позволяет одинаково обновить базы на компьютере разработчика и на сервере и отслеживать, какие изменения уже применены. Хорошая миграция имеет понятный номер и проверяемый результат."
};
