import type { Task } from "./course";

const parkingProfile = "parking-database" as const;
const terms = ["JOIN", "WHERE", "GROUP BY"];
const example = "SELECT owners.last_name, cars.plate FROM owners JOIN cars ON cars.owner_id = owners.id_owner;";

export const parkingFullTasks: Task[] = [
  {id:"parking-real-owner-cars",module:"Работы 1–4 · Автопарковка",title:"Машины владельца №52",minutes:5,concept:"Выгрузки владельцев и машин связаны по идентификатору владельца.",terms,example,prompt:"По полному набору из файла преподавателя выведи марку, модель и госномер машин владельца 52.",starter:"-- Используй таблицы cars и owners",solution:"SELECT cars.brand, cars.model, cars.plate FROM cars JOIN owners ON owners.id_owner = cars.owner_id WHERE owners.id_owner = 52 ORDER BY cars.brand, cars.model;",hints:["Связь: owners.id_owner и cars.owner_id.","Оставь строки, где id_owner равен 52."],seed:"",seedProfile:parkingProfile,ordered:true},
  {id:"parking-real-plate-search",module:"Работы 1–4 · Автопарковка",title:"Поиск машины по госномеру",minutes:4,concept:"Точный поиск по уникальному номеру возвращает карточку нужного автомобиля.",terms:["WHERE","условие"],example:"SELECT * FROM cars WHERE plate = 'А123ВС77';",prompt:"Найди автомобиль по госномеру Е678ХМ190. Выведи все его столбцы.",starter:"-- Выполни точный поиск по plate",solution:"SELECT * FROM cars WHERE plate = 'Е678ХМ190';",hints:["Номер хранится в столбце plate.","Текст госномера укажи в одинарных кавычках."],seed:"",seedProfile:parkingProfile},
  {id:"parking-real-owner-count",module:"Работы 1–4 · Автопарковка",title:"Число машин у каждого владельца",minutes:6,concept:"JOIN и GROUP BY позволяют собрать число автомобилей вместе с именем владельца.",terms:["JOIN","COUNT","GROUP BY"],example,prompt:"Посчитай автомобили каждого владельца. Выведи имя, фамилию и cars_count, от большего автопарка к меньшему.",starter:"-- Сгруппируй машины по владельцу",solution:"SELECT owners.last_name, owners.first_name, COUNT(cars.id) AS cars_count FROM owners JOIN cars ON cars.owner_id = owners.id_owner GROUP BY owners.id_owner, owners.last_name, owners.first_name ORDER BY cars_count DESC, owners.id_owner;",hints:["Свяжи таблицы по owner_id.","Сгруппируй по владельцу и посчитай cars.id."],seed:"",seedProfile:parkingProfile,ordered:true},
  {id:"parking-real-most-cars",module:"Работы 1–4 · Автопарковка",title:"Владелец с самым большим автопарком",minutes:6,concept:"Отсортируй число машин владельца по убыванию и оставь лидера.",terms:["COUNT","GROUP BY","LIMIT"],example:"ORDER BY cars_count DESC LIMIT 1",prompt:"Найди владельца с наибольшим числом автомобилей. Выведи его имя, фамилию и cars_count.",starter:"-- Сгруппируй машины по владельцу",solution:"SELECT owners.first_name, owners.last_name, COUNT(cars.id) AS cars_count FROM owners JOIN cars ON cars.owner_id = owners.id_owner GROUP BY owners.id_owner, owners.first_name, owners.last_name ORDER BY cars_count DESC, owners.id_owner LIMIT 1;",hints:["Сначала посчитай число машин по каждому владельцу.","Отсортируй по cars_count DESC и добавь LIMIT 1."],seed:"",seedProfile:parkingProfile,ordered:true},
  {id:"parking-real-body-types",module:"Работы 1–4 · Автопарковка",title:"Самый редкий тип кузова",minutes:7,concept:"Сгруппируй автомобили по типу кузова и используй оконный ранг, чтобы найти наименьшее количество.",terms:["GROUP BY","RANK","CTE"],example:"RANK() OVER (ORDER BY cars_count)",prompt:"Найди тип кузова, который встречается реже всего. Покажи тип и cars_count; если типов с одинаковым минимумом несколько, покажи их все.",starter:"-- Сначала посчитай машины по body_type",solution:"WITH counts AS (SELECT body_type, COUNT(*) AS cars_count FROM cars GROUP BY body_type), ranked AS (SELECT body_type, cars_count, RANK() OVER (ORDER BY cars_count) AS place FROM counts) SELECT body_type, cars_count FROM ranked WHERE place = 1;",hints:["В первом CTE посчитай машины каждого body_type.","Во втором CTE назначь RANK по возрастанию cars_count."],seed:"",seedProfile:parkingProfile},
  {id:"parking-real-owner-debt",module:"Работы 1–4 · Автопарковка",title:"Задолженность по владельцам",minutes:7,concept:"Долг по каждой сессии можно агрегировать по владельцу через автомобиль.",terms:["JOIN","SUM","GROUP BY"],example:"SUM(sessions.debt_amount)",prompt:"По всем парковочным сессиям посчитай общий долг каждого владельца. Покажи фамилию и total_debt, начиная с самого большого долга.",starter:"-- Свяжи owners, cars и sessions",solution:"SELECT owners.last_name, SUM(sessions.debt_amount) AS total_debt FROM owners JOIN cars ON cars.owner_id = owners.id_owner JOIN sessions ON sessions.car_id = cars.id GROUP BY owners.id_owner, owners.last_name ORDER BY total_debt DESC;",hints:["Путь связи: owners → cars → sessions.","Используй SUM по debt_amount и GROUP BY владельца."],seed:"",seedProfile:parkingProfile,ordered:true},
  {id:"parking-real-session-totals",module:"Работы 1–4 · Автопарковка",title:"Начислено и оплачено по зонам",minutes:7,concept:"Несколько агрегатов дают сводку по всем парковочным зонам в одном запросе.",terms:["JOIN","SUM","GROUP BY"],example:"SUM(charged_amount), SUM(paid_amount)",prompt:"Для каждой зоны посчитай сумму начислений и оплат по парковочным сессиям. Выведи zone, charged_total и paid_total.",starter:"-- Свяжи sessions с парковочными местами",solution:"SELECT parking_spots.zone, SUM(sessions.charged_amount) AS charged_total, SUM(sessions.paid_amount) AS paid_total FROM sessions JOIN parking_spots ON parking_spots.id = sessions.spot_id GROUP BY parking_spots.zone ORDER BY parking_spots.zone;",hints:["Связь с тарифной таблицей идёт через spot_id.","Сложи charged_amount и paid_amount отдельно для каждой зоны."],seed:"",seedProfile:parkingProfile,ordered:true},
];
