import type { Task } from "./course";

// Curated SQLite exercises adapted from the teacher's practical work files.
// The original files use MySQL features; these tasks keep their learning goals
// while remaining runnable in the browser's SQLite sandbox.
export const teacherTasks: Task[] = [
  {
    id: "parking-cars-filter", module: "Работы 1–4 · Автопарковка", title: "Найди автомобили Cadillac", minutes: 4,
    concept: "WHERE отбирает строки по условию. Текст сравнивается в одинарных кавычках.", terms: ["SELECT", "WHERE"],
    example: "SELECT model, plate FROM cars WHERE brand = 'Cadillac';",
    prompt: "Выведи модели и госномера всех автомобилей Cadillac. Назови столбцы model и plate.", starter: "-- Напиши запрос к таблице cars",
    solution: "SELECT model, plate FROM cars WHERE brand = 'Cadillac';", hints: ["Нужна таблица cars и условие по brand.", "Выбери model, plate и добавь WHERE brand = 'Cadillac'."],
    seed: "CREATE TABLE cars (id INTEGER PRIMARY KEY, owner_id INTEGER, brand TEXT, model TEXT, plate TEXT, body_type TEXT); INSERT INTO cars VALUES (1,4,'BMW','X3','А123ВС77','Кроссовер'),(2,4,'Cadillac','SRX','Е678ХМ190','Внедорожник'),(3,52,'Nissan','Almera','М263НК177','Седан'),(4,60,'Cadillac','Escalade','К777КК99','Внедорожник'),(5,8,'BMW','X5','А555АА50','Кроссовер'),(6,52,'Kia','Rio','О123ОО777','Седан');",
  },
  {
    id: "parking-owner-count", module: "Работы 1–4 · Автопарковка", title: "Автомобили каждого владельца", minutes: 5,
    concept: "GROUP BY собирает автомобили владельца в одну группу, а COUNT(*) считает записи.", terms: ["GROUP BY", "COUNT", "ORDER BY"],
    example: "SELECT owner_id, COUNT(*) AS cars_count FROM cars GROUP BY owner_id;",
    prompt: "Посчитай автомобили каждого владельца. Выведи owner_id и cars_count, сначала владельцев с самым большим автопарком.", starter: "-- Сгруппируй автомобили по owner_id",
    solution: "SELECT owner_id, COUNT(*) AS cars_count FROM cars GROUP BY owner_id ORDER BY cars_count DESC, owner_id;", hints: ["Группируй по owner_id.", "Добавь COUNT(*) и сортировку по cars_count по убыванию."],
    seed: "CREATE TABLE cars (id INTEGER PRIMARY KEY, owner_id INTEGER, brand TEXT, model TEXT, plate TEXT, body_type TEXT); INSERT INTO cars VALUES (1,4,'BMW','X3','А123ВС77','Кроссовер'),(2,4,'Cadillac','SRX','Е678ХМ190','Внедорожник'),(3,52,'Nissan','Almera','М263НК177','Седан'),(4,60,'Cadillac','Escalade','К777КК99','Внедорожник'),(5,8,'BMW','X5','А555АА50','Кроссовер'),(6,52,'Kia','Rio','О123ОО777','Седан');",
  },
  {
    id: "parking-top-brands", module: "Работы 1–4 · Автопарковка", title: "Популярные марки", minutes: 5,
    concept: "Агрегат COUNT считает автомобили, а GROUP BY делает отдельный итог для каждой марки.", terms: ["COUNT", "GROUP BY", "LIMIT"],
    example: "SELECT brand, COUNT(*) AS total FROM cars GROUP BY brand ORDER BY total DESC;",
    prompt: "Покажи три самые частые марки. Результат: brand и total, от большего количества к меньшему.", starter: "-- Посчитай автомобили по маркам",
    solution: "SELECT brand, COUNT(*) AS total FROM cars GROUP BY brand ORDER BY total DESC, brand LIMIT 3;", hints: ["Сгруппируй строки по brand.", "Отсортируй COUNT(*) по убыванию и оставь 3 строки."],
    seed: "CREATE TABLE cars (id INTEGER PRIMARY KEY, owner_id INTEGER, brand TEXT, model TEXT, plate TEXT, body_type TEXT); INSERT INTO cars VALUES (1,4,'BMW','X3','А123ВС77','Кроссовер'),(2,4,'Cadillac','SRX','Е678ХМ190','Внедорожник'),(3,52,'Nissan','Almera','М263НК177','Седан'),(4,60,'Cadillac','Escalade','К777КК99','Внедорожник'),(5,8,'BMW','X5','А555АА50','Кроссовер'),(6,52,'Kia','Rio','О123ОО777','Седан');",
  },
  {
    id: "parking-cheapest-zone", module: "Работы 1–4 · Автопарковка", title: "Средняя цена по зонам", minutes: 5,
    concept: "GROUP BY считает сводку для каждой зоны. AVG находит среднюю стоимость.", terms: ["AVG", "GROUP BY", "HAVING"],
    example: "SELECT zone, AVG(daily_rate) AS avg_rate FROM parking_spots GROUP BY zone;",
    prompt: "Найди зоны, где средняя цена выше 1000 рублей. Выведи zone и avg_rate, от дорогой зоны к дешёвой.", starter: "-- Сгруппируй места по zone",
    solution: "SELECT zone, AVG(daily_rate) AS avg_rate FROM parking_spots GROUP BY zone HAVING AVG(daily_rate) > 1000 ORDER BY avg_rate DESC;", hints: ["Для фильтра групп используй HAVING.", "Условие после группировки: HAVING AVG(daily_rate) > 1000."],
    seed: "", seedProfile: "parking-spots",
  },
  {
    id: "parking-window-rank", module: "Работы 1–4 · Автопарковка", title: "Дешёвое место в каждой зоне", minutes: 7,
    concept: "Оконная функция RANK нумерует строки внутри каждой зоны, не объединяя их.", terms: ["RANK", "OVER", "PARTITION BY"],
    example: "RANK() OVER (PARTITION BY zone ORDER BY daily_rate)",
    prompt: "Для каждого места выведи spot_number, zone, daily_rate и номер места по цене внутри зоны (price_rank). Самые дешёвые должны получить ранг 1.", starter: "-- Используй RANK() OVER (...)",
    solution: "SELECT spot_number, zone, daily_rate, RANK() OVER (PARTITION BY zone ORDER BY daily_rate) AS price_rank FROM parking_spots ORDER BY zone, price_rank;", hints: ["Раздели окно по zone и отсортируй по daily_rate.", "Вызов: RANK() OVER (PARTITION BY zone ORDER BY daily_rate)."],
    seed: "", seedProfile: "parking-spots",
    ordered: true,
  },
  {
    id: "parking-session-debt", module: "Работы 1–4 · Автопарковка", title: "Найди долги по парковке", minutes: 6,
    concept: "JOIN соединяет сессию парковки с автомобилем по идентификатору. WHERE оставляет только неоплаченные суммы.", terms: ["JOIN", "WHERE", "ORDER BY"],
    example: "SELECT cars.plate, sessions.debt FROM cars JOIN sessions ON cars.id = sessions.car_id;",
    prompt: "Выведи госномер и сумму долга для сессий, где долг больше нуля. Отсортируй по убыванию долга.", starter: "-- Соедини cars и sessions",
    solution: "SELECT cars.plate, sessions.debt FROM cars JOIN sessions ON cars.id = sessions.car_id WHERE sessions.debt > 0 ORDER BY sessions.debt DESC;", hints: ["Связь: cars.id = sessions.car_id.", "После JOIN добавь WHERE debt > 0 и ORDER BY debt DESC."],
    seed: "CREATE TABLE cars (id INTEGER PRIMARY KEY, plate TEXT, brand TEXT); CREATE TABLE sessions (id INTEGER PRIMARY KEY, car_id INTEGER, debt INTEGER); INSERT INTO cars VALUES (1,'М263НК177','Nissan'),(2,'А154ТЕ190','Cadillac'),(3,'Е678ХМ190','Suzuki'); INSERT INTO sessions VALUES (1000,1,555000),(1001,2,0),(1002,3,12500);",
  },
  {
    id: "athletes-case", module: "Работа 5 · Аналитика", title: "Подбери спортивную награду", minutes: 5,
    concept: "CASE проверяет условия по порядку и возвращает подпись для каждой строки.", terms: ["CASE", "WHEN", "AND"],
    example: "CASE WHEN place = 1 THEN 'Золото' ELSE 'Участник' END",
    prompt: "Выведи имя, страну и оценку результата: «Молодец» для мест 1 или 2 с призовыми больше 5000; иначе «Продолжай тренироваться».", starter: "-- Добавь выражение CASE к таблице athletes",
    solution: "SELECT name, country, CASE WHEN place IN (1, 2) AND prize > 5000 THEN 'Молодец' ELSE 'Продолжай тренироваться' END AS result FROM athletes;", hints: ["Проверь место через IN (1, 2).", "Объедини место и размер приза через AND внутри WHEN."],
    seed: "CREATE TABLE athletes (id INTEGER PRIMARY KEY, name TEXT, country TEXT, birth_date TEXT, place INTEGER, prize INTEGER); INSERT INTO athletes VALUES (1,'Алина','Беларусь','2001-07-12',1,8200),(2,'Марк','Россия','1999-02-03',2,5100),(3,'Ева','Казахстан','2003-11-21',3,9000),(4,'Анна','Беларусь','2000-06-01',2,4500),(5,'Илья','Россия','2002-04-18',1,12000);",
  },
  {
    id: "athletes-country-average", module: "Работа 5 · Аналитика", title: "Призовые выше среднего по стране", minutes: 7,
    concept: "AVG() OVER (PARTITION BY ...) считает среднее внутри группы и оставляет исходные строки.", terms: ["AVG", "OVER", "PARTITION BY"],
    example: "AVG(prize) OVER (PARTITION BY country)",
    prompt: "Покажи имя, страну, призовые и средние призовые по стране только для спортсменов, чей приз выше среднего в своей стране.", starter: "-- Рассчитай среднее призовых для каждой страны",
    solution: "WITH scored AS (SELECT name, country, prize, AVG(prize) OVER (PARTITION BY country) AS country_avg FROM athletes) SELECT name, country, prize, country_avg FROM scored WHERE prize > country_avg;", hints: ["Сначала добавь среднее по стране оконной функцией.", "Помести расчёт в CTE, а затем сравни prize с country_avg."],
    seed: "CREATE TABLE athletes (id INTEGER PRIMARY KEY, name TEXT, country TEXT, birth_date TEXT, place INTEGER, prize INTEGER); INSERT INTO athletes VALUES (1,'Алина','Беларусь','2001-07-12',1,8200),(2,'Марк','Россия','1999-02-03',2,5100),(3,'Ева','Казахстан','2003-11-21',3,9000),(4,'Анна','Беларусь','2000-06-01',2,4500),(5,'Илья','Россия','2002-04-18',1,12000);",
  },
  {
    id: "sugar-stock-balance", module: "Работа 9 · Аудит компании", title: "Баланс выпуска и списаний", minutes: 7,
    concept: "Условная агрегация с CASE позволяет посчитать несколько итогов одним проходом по таблице.", terms: ["SUM", "CASE", "GROUP BY"],
    example: "SUM(CASE WHEN movement_type = 'sale' THEN quantity ELSE 0 END)",
    prompt: "Посчитай выпуск, продажи, контроль качества и брак по таблице движений запасов. Выведи по одному числу в столбцах produced, sold, quality_check, damaged.", starter: "-- Используй SUM(CASE WHEN ...)",
    solution: "SELECT SUM(CASE WHEN movement_type = 'production' THEN quantity ELSE 0 END) AS produced, SUM(CASE WHEN movement_type = 'sale' THEN quantity ELSE 0 END) AS sold, SUM(CASE WHEN movement_type = 'quality_check' THEN quantity ELSE 0 END) AS quality_check, SUM(CASE WHEN movement_type = 'damaged' THEN quantity ELSE 0 END) AS damaged FROM stock_movements;", hints: ["Каждый итог — отдельная сумма с CASE.", "Например: SUM(CASE WHEN movement_type = 'sale' THEN quantity ELSE 0 END)."],
    seed: "CREATE TABLE stock_movements (id INTEGER PRIMARY KEY, movement_type TEXT, quantity INTEGER); INSERT INTO stock_movements VALUES (1,'production',100),(2,'sale',12),(3,'quality_check',70),(4,'damaged',3),(5,'production',80),(6,'sale',20),(7,'quality_check',60),(8,'damaged',2);",
  },
  {
    id: "sugar-monthly-trend", module: "Работа 9 · Аудит компании", title: "Динамика выпуска по месяцам", minutes: 8,
    concept: "CTE собирает промежуточные итоги, а LAG показывает значение предыдущей строки.", terms: ["WITH", "GROUP BY", "LAG"],
    example: "LAG(produced) OVER (ORDER BY month)",
    prompt: "Посчитай выпуск по месяцам и покажи также выпуск прошлого месяца (previous_month). Используй таблицу monthly_production.", starter: "-- Сначала сгруппируй выпуск по месяцу",
    solution: "WITH totals AS (SELECT month, SUM(quantity) AS produced FROM monthly_production GROUP BY month) SELECT month, produced, LAG(produced) OVER (ORDER BY month) AS previous_month FROM totals ORDER BY month;", hints: ["В CTE посчитай SUM(quantity) для каждого month.", "Снаружи примени LAG(produced) OVER (ORDER BY month)."],
    seed: "CREATE TABLE monthly_production (month TEXT, quantity INTEGER); INSERT INTO monthly_production VALUES ('2026-07',120),('2026-07',30),('2026-08',160),('2026-09',90);",
    ordered: true,
  },
  {
    id: "globus-honest-rating", module: "Работа 10 · Магазин", title: "Рейтинг магазинов по честным отзывам", minutes: 7,
    concept: "LEFT JOIN сохраняет магазины без отзывов. GROUP BY собирает отзывы магазина, а AVG считает рейтинг.", terms: ["LEFT JOIN", "AVG", "GROUP BY"],
    example: "SELECT store_id, AVG(rating) FROM reviews GROUP BY store_id;",
    prompt: "Для каждого магазина посчитай среднюю оценку только по честным отзывам (honest = 1). Выведи название магазина и рейтинг от высокого к низкому.", starter: "-- Соедини stores и reviews",
    solution: "SELECT stores.name, AVG(reviews.rating) AS avg_rating FROM stores LEFT JOIN reviews ON reviews.store_id = stores.id AND reviews.honest = 1 GROUP BY stores.id, stores.name ORDER BY avg_rating DESC;", hints: ["Условие honest = 1 включи в соединение отзывов.", "Сгруппируй по id и name магазина, используй AVG(rating)."],
    seed: "CREATE TABLE stores (id INTEGER PRIMARY KEY, name TEXT, store_type TEXT); CREATE TABLE reviews (id INTEGER PRIMARY KEY, store_id INTEGER, rating REAL, honest INTEGER); INSERT INTO stores VALUES (1,'Глобус Север','гипермаркет'),(2,'Глобус Центр','гипермаркет'),(3,'Магазин у дома','магазин'); INSERT INTO reviews VALUES (1,1,4.5,1),(2,1,5,0),(3,1,4,1),(4,2,4.8,1),(5,2,4.6,1),(6,3,5,1);",
  },
  {
    id: "globus-final-price", module: "Работа 10 · Магазин", title: "Выбери последнюю цену товара", minutes: 8,
    concept: "ROW_NUMBER нумерует историю цены отдельно для каждого товара. Оставив первую строку, получаем последнюю запись.", terms: ["ROW_NUMBER", "PARTITION BY", "CTE"],
    example: "ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY valid_from DESC)",
    prompt: "Найди последнюю цену каждого товара на дату 2026-10-01: возьми только записи с valid_from не позже этой даты. Выведи товар, цену и дату.", starter: "-- Используй ROW_NUMBER() и CTE",
    solution: "WITH ranked AS (SELECT products.name, price_log.price, price_log.valid_from, ROW_NUMBER() OVER (PARTITION BY price_log.product_id ORDER BY price_log.valid_from DESC) AS row_num FROM price_log JOIN products ON products.id = price_log.product_id WHERE price_log.valid_from <= '2026-10-01') SELECT name, price, valid_from FROM ranked WHERE row_num = 1 ORDER BY name;", hints: ["Сначала отфильтруй даты и пронумеруй записи товара от новых к старым.", "Внешний запрос оставляет row_num = 1."],
    seed: "CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT); CREATE TABLE price_log (id INTEGER PRIMARY KEY, product_id INTEGER, price REAL, valid_from TEXT); INSERT INTO products VALUES (1,'Гречка'),(2,'Яйца'),(3,'Макароны'); INSERT INTO price_log VALUES (1,1,110,'2026-09-01'),(2,1,95,'2026-09-25'),(3,1,120,'2026-10-05'),(4,2,160,'2026-09-20'),(5,2,155,'2026-09-30'),(6,3,80,'2026-09-10');",
    ordered: true,
  },
  {
    id: "series-top-episodes", module: "Работы 6 и 8 · Проектирование БД", title: "Лучшие эпизоды сериала", minutes: 7,
    concept: "JOIN соединяет оценки с эпизодами. HAVING оставляет эпизоды, которые получили достаточно оценок.", terms: ["JOIN", "AVG", "HAVING"],
    example: "SELECT episode_id, AVG(score) FROM ratings GROUP BY episode_id HAVING COUNT(*) >= 3;",
    prompt: "Для каждого сериала покажи эпизоды со средним рейтингом выше 8, если эпизод получил минимум 3 оценки. Выведи название сериала, эпизод и средний рейтинг.", starter: "-- Объедини shows, episodes и ratings",
    solution: "SELECT shows.title, episodes.title, AVG(ratings.score) AS avg_score FROM shows JOIN episodes ON episodes.show_id = shows.id JOIN ratings ON ratings.episode_id = episodes.id GROUP BY shows.id, shows.title, episodes.id, episodes.title HAVING COUNT(ratings.id) >= 3 AND AVG(ratings.score) > 8 ORDER BY avg_score DESC;", hints: ["Сначала свяжи сериалы, эпизоды и оценки через JOIN.", "Группируй по эпизоду, а обе проверки числа и среднего добавь в HAVING."],
    seed: "CREATE TABLE shows (id INTEGER PRIMARY KEY, title TEXT); CREATE TABLE episodes (id INTEGER PRIMARY KEY, show_id INTEGER, title TEXT); CREATE TABLE ratings (id INTEGER PRIMARY KEY, episode_id INTEGER, score REAL); INSERT INTO shows VALUES (1,'Орбита'),(2,'Северный берег'); INSERT INTO episodes VALUES (10,1,'Первый сигнал'),(11,1,'Эхо'),(20,2,'Переезд'); INSERT INTO ratings VALUES (1,10,9),(2,10,8.5),(3,10,9.5),(4,11,10),(5,11,7),(6,20,8),(7,20,8.5),(8,20,9);",
    ordered: true,
  },
  {
    id: "case-camera-trail", module: "Работа 7 · Расследование", title: "Собери маршрут автомобиля", minutes: 6,
    concept: "JOIN связывает запись камеры с автомобилем по car_id. Фильтр по госномеру оставляет нужную машину.", terms: ["JOIN", "WHERE", "ORDER BY"],
    example: "SELECT cars.plate, camera_records.recorded_at FROM camera_records JOIN cars ON cars.id = camera_records.car_id;",
    prompt: "Найди все записи камер для автомобиля с номером М002РТ150. Выведи место камеры и время проезда, сначала более ранние записи.", starter: "-- Соедини camera_records и cars",
    solution: "SELECT camera_records.location, camera_records.recorded_at FROM camera_records JOIN cars ON cars.id = camera_records.car_id WHERE cars.plate = 'М002РТ150' ORDER BY camera_records.recorded_at;", hints: ["В таблице cars найди plate, а точки маршрута хранятся в camera_records.", "Свяжи таблицы по id и car_id, отфильтруй госномер."],
    seed: "CREATE TABLE cars (id INTEGER PRIMARY KEY, plate TEXT, model TEXT); CREATE TABLE camera_records (id INTEGER PRIMARY KEY, car_id INTEGER, location TEXT, recorded_at TEXT); INSERT INTO cars VALUES (1,'М002РТ150','Suzuki SX4'),(2,'К777КК99','ВАЗ 2107'); INSERT INTO camera_records VALUES (1,1,'ТЦ Галактика','2026-09-19 18:14'),(2,2,'ул. Садовая','2026-09-19 18:26'),(3,1,'Промышленное шоссе','2026-09-19 19:02');",
    ordered: true,
  },
  {
    id: "series-design-tables", module: "Работы 6 и 8 · Проектирование БД", title: "Создай основу базы сериалов", minutes: 8,
    concept: "Связанные таблицы хранят сериалы, эпизоды и оценки раздельно. Первичные и внешние ключи связывают записи.", terms: ["CREATE TABLE", "PRIMARY KEY", "FOREIGN KEY"],
    example: "CREATE TABLE episodes (id INTEGER PRIMARY KEY, show_id INTEGER REFERENCES shows(id), title TEXT NOT NULL);",
    prompt: "Создай таблицы shows, episodes и ratings. У каждой таблицы должен быть INTEGER PRIMARY KEY id. Названия обязательны, а эпизод и оценка должны ссылаться на родительскую запись. Оценка — число от 1 до 10.", starter: "-- Создай три связанные таблицы",
    solution: "CREATE TABLE shows (id INTEGER PRIMARY KEY, title TEXT NOT NULL); CREATE TABLE episodes (id INTEGER PRIMARY KEY, show_id INTEGER NOT NULL REFERENCES shows(id), title TEXT NOT NULL); CREATE TABLE ratings (id INTEGER PRIMARY KEY, episode_id INTEGER NOT NULL REFERENCES episodes(id), score REAL NOT NULL CHECK (score >= 1 AND score <= 10));", hints: ["Начни с таблицы shows, затем episodes и ratings.", "Добавь REFERENCES на родительский id и CHECK для диапазона оценки."], seed: "", mode: "state",
  },
];
