import type { Task } from "./course";

type Exercise = Pick<Task, "id" | "title" | "prompt" | "solution" | "terms" | "example" | "hints"> & {
  concept?: string;
  minutes?: number;
  mode?: Task["mode"];
  ordered?: boolean;
  seed?: string;
  seedProfile?: Task["seedProfile"];
};

const exercises: Exercise[] = [
  {id:"spot-all-rows",title:"Просмотр всей парковки",prompt:"Выведи все строки и все столбцы таблицы parking_spots.",solution:"SELECT * FROM parking_spots;",terms:["SELECT","FROM"],example:"SELECT * FROM parking_spots;",hints:["Таблица называется parking_spots.","Звёздочка выбирает все столбцы."],minutes:3},
  {id:"spot-number-zone",title:"Краткий список мест",prompt:"Покажи только номер места и зону. Назови столбцы spot_number и zone.",solution:"SELECT spot_number, zone FROM parking_spots;",terms:["SELECT","FROM"],example:"SELECT spot_number, zone FROM parking_spots;",hints:["Перечисли нужные поля после SELECT.","Источник строк укажи после FROM."],minutes:3},
  {id:"spot-covered-zone",title:"Крытые места",prompt:"Найди места в зонах, название которых содержит слово «Крытая». Выведи номер и зону.",solution:"SELECT spot_number, zone FROM parking_spots WHERE zone LIKE '%Крытая%';",terms:["WHERE","LIKE"],example:"WHERE zone LIKE '%часть текста%'",hints:["Для совпадения по части текста подходит LIKE.","Проценты до и после слова разрешают любой текст вокруг."],minutes:4},
  {id:"spot-price-filter",title:"Места дороже тысячи",prompt:"Покажи номера и цены мест со стоимостью больше 1000 рублей в сутки.",solution:"SELECT spot_number, daily_rate FROM parking_spots WHERE daily_rate > 1000;",terms:["WHERE","условие"],example:"SELECT spot_number FROM parking_spots WHERE daily_rate > 1000;",hints:["Нужен столбец daily_rate.","Оператор > оставляет цены выше заданного числа."],minutes:4},
  {id:"spot-price-order",title:"Сортировка прайса",prompt:"Выведи номер, зону и цену всех мест, отсортированных от дешёвых к дорогим.",solution:"SELECT spot_number, zone, daily_rate FROM parking_spots ORDER BY daily_rate, spot_number;",terms:["ORDER BY","ASC"],example:"ORDER BY daily_rate ASC",hints:["Добавь ORDER BY daily_rate.","ASC — порядок по возрастанию и используется по умолчанию."],minutes:4,ordered:true},
  {id:"spot-total-count",title:"Сколько мест на парковке",prompt:"Посчитай общее количество парковочных мест и назови столбец total.",solution:"SELECT COUNT(*) AS total FROM parking_spots;",terms:["COUNT","AS"],example:"SELECT COUNT(*) AS total FROM parking_spots;",hints:["COUNT(*) считает строки.","Используй псевдоним AS total."],minutes:4},
  {id:"spot-average-rate",title:"Средняя стоимость суток",prompt:"Найди среднюю стоимость места по всей парковке. Назови результат avg_rate.",solution:"SELECT AVG(daily_rate) AS avg_rate FROM parking_spots;",terms:["AVG","AS"],example:"SELECT AVG(daily_rate) AS avg_rate FROM parking_spots;",hints:["AVG вычисляет среднее.","Передай функции столбец daily_rate."],minutes:4},
  {id:"spot-price-bounds",title:"Самая высокая и низкая цена",prompt:"Одной строкой покажи минимальную и максимальную цену с именами min_rate и max_rate.",solution:"SELECT MIN(daily_rate) AS min_rate, MAX(daily_rate) AS max_rate FROM parking_spots;",terms:["MIN","MAX"],example:"SELECT MIN(price), MAX(price) FROM items;",hints:["Нужны две агрегатные функции.","Обе функции применяются к daily_rate."],minutes:4},
  {id:"spot-count-per-zone",title:"Количество мест по зонам",prompt:"Для каждой зоны покажи её название и число мест (spots_count). Отсортируй по числу мест по убыванию.",solution:"SELECT zone, COUNT(*) AS spots_count FROM parking_spots GROUP BY zone ORDER BY spots_count DESC;",terms:["GROUP BY","COUNT","ORDER BY"],example:"GROUP BY zone",hints:["Сгруппируй строки по zone.","Сортируй результат по псевдониму spots_count."],minutes:5,ordered:true},
  {id:"spot-potential-revenue",title:"Потенциальная выручка за сутки",prompt:"Посчитай сумму всех суточных тарифов, как если бы каждое место было занято. Столбец назови potential_revenue.",solution:"SELECT SUM(daily_rate) AS potential_revenue FROM parking_spots;",terms:["SUM"],example:"SELECT SUM(daily_rate) AS total FROM parking_spots;",hints:["Сумму значений считает SUM.","Просуммируй daily_rate."],minutes:4},
  {id:"spot-average-by-zone",title:"Средняя цена каждой зоны",prompt:"Покажи среднюю стоимость отдельно по каждой зоне: zone и avg_rate. От дорогой средней к дешёвой.",solution:"SELECT zone, AVG(daily_rate) AS avg_rate FROM parking_spots GROUP BY zone ORDER BY avg_rate DESC;",terms:["AVG","GROUP BY"],example:"SELECT zone, AVG(daily_rate) FROM parking_spots GROUP BY zone;",hints:["Сгруппируй по zone.","Применяй AVG к daily_rate."],minutes:5,ordered:true},
  {id:"spot-distinct-zones",title:"Сколько разных зон",prompt:"Посчитай число уникальных зон и назови результат zones_count.",solution:"SELECT COUNT(DISTINCT zone) AS zones_count FROM parking_spots;",terms:["COUNT","DISTINCT"],example:"COUNT(DISTINCT zone)",hints:["DISTINCT убирает повторы.","COUNT(DISTINCT zone) считает уникальные зоны."],minutes:4},
  {id:"spot-empty-descriptions",title:"Карточки без описания",prompt:"Посчитай места, у которых нет описания (NULL). Назови результат missing_descriptions.",solution:"SELECT COUNT(*) AS missing_descriptions FROM parking_spots WHERE description IS NULL;",terms:["NULL","IS NULL"],example:"WHERE description IS NULL",hints:["NULL проверяют через IS NULL.","Фильтруй строки, где description IS NULL."],minutes:4},
  {id:"spot-large-zones",title:"Крупные зоны",prompt:"Покажи зоны, где больше 10 мест. Выведи zone и spots_count.",solution:"SELECT zone, COUNT(*) AS spots_count FROM parking_spots GROUP BY zone HAVING COUNT(*) > 10 ORDER BY zone;",terms:["GROUP BY","HAVING"],example:"HAVING COUNT(*) > 10",hints:["Сначала сгруппируй строки по зоне.","Условие на результат агрегирования добавь через HAVING."],minutes:5,ordered:true},
  {id:"spot-high-average-zones",title:"Дорогие зоны",prompt:"Покажи зоны со средней стоимостью выше 1500 рублей. Выведи zone и avg_rate.",solution:"SELECT zone, AVG(daily_rate) AS avg_rate FROM parking_spots GROUP BY zone HAVING AVG(daily_rate) > 1500 ORDER BY avg_rate DESC;",terms:["AVG","HAVING"],example:"HAVING AVG(daily_rate) > 1500",hints:["Фильтруй группы через HAVING.","Условие проверяет среднее, а не отдельную цену."],minutes:5,ordered:true},
  {id:"spot-above-vip",title:"Дороже VIP-01",prompt:"Найди все места, которые дороже VIP-01. Получи цену VIP-01 подзапросом, не подставляя её числом вручную.",solution:"SELECT spot_number, daily_rate FROM parking_spots WHERE daily_rate > (SELECT daily_rate FROM parking_spots WHERE spot_number = 'VIP-01');",terms:["подзапрос","WHERE"],example:"WHERE price > (SELECT price FROM items WHERE id = 1)",hints:["Внутренний запрос должен найти тариф VIP-01.","Сравни daily_rate с результатом подзапроса."],minutes:6},
  {id:"spot-zone-price-spread",title:"Зоны с большим разбросом цен",prompt:"Найди зоны, где разница между самой дорогой и дешёвой ценой больше 500 рублей. Покажи zone и price_spread.",solution:"SELECT zone, MAX(daily_rate) - MIN(daily_rate) AS price_spread FROM parking_spots GROUP BY zone HAVING MAX(daily_rate) - MIN(daily_rate) > 500 ORDER BY price_spread DESC;",terms:["MAX","MIN","HAVING"],example:"MAX(daily_rate) - MIN(daily_rate)",hints:["Вычти MIN из MAX внутри каждой группы.","Оставь только группы, где разница превышает 500."],minutes:6,ordered:true},
  {id:"spot-global-minimum",title:"Места по минимальному тарифу",prompt:"Выведи номера и зоны мест с самой низкой ценой на всей парковке. Найди минимум подзапросом.",solution:"SELECT spot_number, zone, daily_rate FROM parking_spots WHERE daily_rate = (SELECT MIN(daily_rate) FROM parking_spots);",terms:["MIN","подзапрос"],example:"WHERE price = (SELECT MIN(price) FROM items)",hints:["Подзапрос вычисляет минимальную цену.","Во внешнем запросе сравни daily_rate с этим минимумом."],minutes:5},
  {id:"spot-zone-vs-standard",title:"Сравнение размеров зон",prompt:"Найди зоны, где мест меньше, чем в зоне «Стандарт». Выведи zone и spots_count.",solution:"SELECT zone, COUNT(*) AS spots_count FROM parking_spots GROUP BY zone HAVING COUNT(*) < (SELECT COUNT(*) FROM parking_spots WHERE zone = 'Стандарт') ORDER BY spots_count;",terms:["GROUP BY","подзапрос","HAVING"],example:"HAVING COUNT(*) < (SELECT COUNT(*) FROM parking_spots WHERE zone = 'Стандарт')",hints:["Подзапрос посчитает места в зоне Стандарт.","Сравни число строк каждой группы с результатом подзапроса."],minutes:6,ordered:true},
  {id:"spot-above-zone-average",title:"Дороже соседей по зоне",prompt:"Покажи номера, зоны и цены мест, где цена выше средней цены этой же зоны. Сравни каждую строку с её группой.",solution:"SELECT p.spot_number, p.zone, p.daily_rate FROM parking_spots AS p WHERE p.daily_rate > (SELECT AVG(p2.daily_rate) FROM parking_spots AS p2 WHERE p2.zone = p.zone) ORDER BY p.zone, p.daily_rate DESC;",terms:["коррелированный подзапрос","AVG"],example:"WHERE price > (SELECT AVG(other.price) FROM items AS other WHERE other.category = items.category)",hints:["Подзапрос должен использовать зону текущей строки.","Свяжи внутренний p2.zone с внешним p.zone."],minutes:7,ordered:true},
  {id:"spot-zone-no-cheap",title:"Зоны без дешёвых мест",prompt:"Найди зоны, в которых нет ни одного места дешевле 500 рублей. Покажи название зоны.",solution:"SELECT DISTINCT p.zone FROM parking_spots AS p WHERE NOT EXISTS (SELECT 1 FROM parking_spots AS cheap WHERE cheap.zone = p.zone AND cheap.daily_rate < 500) ORDER BY p.zone;",terms:["NOT EXISTS","подзапрос"],example:"WHERE NOT EXISTS (SELECT 1 FROM ...)",hints:["Проверь существование дешёвого места в той же зоне.","NOT EXISTS оставит зоны, где подзапрос не находит строк."],minutes:7,ordered:true},
  {id:"spot-row-number",title:"Нумерация прайса",prompt:"Пронумеруй все места от самой низкой цены к высокой функцией ROW_NUMBER. Выведи spot_number, daily_rate и place_no.",solution:"SELECT spot_number, daily_rate, ROW_NUMBER() OVER (ORDER BY daily_rate, spot_number) AS place_no FROM parking_spots ORDER BY place_no;",terms:["ROW_NUMBER","OVER"],example:"ROW_NUMBER() OVER (ORDER BY daily_rate)",hints:["ROW_NUMBER нумерует строки окна.","Добавь OVER с сортировкой по цене."],minutes:6,ordered:true},
  {id:"spot-window-average",title:"Отклонение от средней цены зоны",prompt:"Для каждого места выведи цену, среднюю цену его зоны (zone_avg) и разницу между ними (difference). Используй AVG OVER.",solution:"SELECT spot_number, zone, daily_rate, AVG(daily_rate) OVER (PARTITION BY zone) AS zone_avg, daily_rate - AVG(daily_rate) OVER (PARTITION BY zone) AS difference FROM parking_spots ORDER BY zone, spot_number;",terms:["AVG","OVER","PARTITION BY"],example:"AVG(daily_rate) OVER (PARTITION BY zone)",hints:["Оконная функция оставляет отдельной каждую строку.","Раздели окно по zone, затем вычти среднее из цены."],minutes:7,ordered:true},
  {id:"spot-top-price-levels",title:"Три верхних ценовых уровня",prompt:"Выведи места, относящиеся к трём самым высоким уникальным ценовым уровням. Используй DENSE_RANK и покажи price_level.",solution:"WITH ranked AS (SELECT spot_number, daily_rate, DENSE_RANK() OVER (ORDER BY daily_rate DESC) AS price_level FROM parking_spots) SELECT spot_number, daily_rate, price_level FROM ranked WHERE price_level <= 3 ORDER BY price_level, spot_number;",terms:["DENSE_RANK","CTE","WITH"],example:"DENSE_RANK() OVER (ORDER BY daily_rate DESC)",hints:["DENSE_RANK назначает одинаковый ранг одинаковым ценам.","Помести ранжирование в CTE и оставь уровни до 3."],minutes:7,ordered:true},
  {id:"spot-price-quartiles",title:"Ценовые группы",prompt:"Разбей места на четыре ценовые группы функцией NTILE(4). Выведи номер, цену и группу price_group.",solution:"SELECT spot_number, daily_rate, NTILE(4) OVER (ORDER BY daily_rate, spot_number) AS price_group FROM parking_spots ORDER BY price_group, daily_rate;",terms:["NTILE","OVER"],example:"NTILE(4) OVER (ORDER BY daily_rate)",hints:["NTILE делит отсортированные строки на группы.","Передай 4 в NTILE и отсортируй окно по цене."],minutes:6,ordered:true},
  {id:"spot-most-expensive-per-zone",title:"Самое дорогое место каждой зоны",prompt:"Для каждого места покажи цену самого дорогого места его зоны (zone_max). Используй FIRST_VALUE.",solution:"SELECT spot_number, zone, daily_rate, FIRST_VALUE(daily_rate) OVER (PARTITION BY zone ORDER BY daily_rate DESC) AS zone_max FROM parking_spots ORDER BY zone, spot_number;",terms:["FIRST_VALUE","PARTITION BY"],example:"FIRST_VALUE(daily_rate) OVER (PARTITION BY zone ORDER BY daily_rate DESC)",hints:["Раздели окно по зоне.","Самую высокую цену поставь первой сортировкой DESC."],minutes:7,ordered:true},
  {id:"spot-cte-neighbors",title:"Сколько мест-соседей",prompt:"С помощью CTE посчитай количество мест каждой зоны, затем выведи эти данные для каждого места как zone_size.",solution:"WITH zone_counts AS (SELECT zone, COUNT(*) AS zone_size FROM parking_spots GROUP BY zone) SELECT parking_spots.spot_number, parking_spots.zone, zone_counts.zone_size FROM parking_spots JOIN zone_counts ON zone_counts.zone = parking_spots.zone ORDER BY parking_spots.zone, parking_spots.spot_number;",terms:["WITH","JOIN","GROUP BY"],example:"WITH zone_counts AS (...) SELECT ... FROM parking_spots JOIN zone_counts ...",hints:["В CTE сгруппируй строки по zone.","Присоедини zone_counts к каждой строке по названию зоны."],minutes:7,ordered:true},
  {id:"spot-most-expensive-zone",title:"Зона с самой высокой средней ценой",prompt:"Двумя CTE найди зону с максимальной средней стоимостью. Выведи zone и avg_rate.",solution:"WITH zone_rates AS (SELECT zone, AVG(daily_rate) AS avg_rate FROM parking_spots GROUP BY zone), ranked AS (SELECT zone, avg_rate, RANK() OVER (ORDER BY avg_rate DESC) AS place FROM zone_rates) SELECT zone, avg_rate FROM ranked WHERE place = 1;",terms:["WITH","AVG","RANK"],example:"WITH totals AS (...), ranked AS (...) SELECT ...",hints:["Первый CTE считает средние цены по зонам.","Второй CTE ранжирует средние цены, после чего оставь place = 1."],minutes:7},
  {id:"spot-case-label",title:"Дорогие и обычные места",prompt:"Покажи номер, цену и метку price_label: «дорогое» при цене от 1000 рублей, иначе «доступное». Используй CASE.",solution:"SELECT spot_number, daily_rate, CASE WHEN daily_rate >= 1000 THEN 'дорогое' ELSE 'доступное' END AS price_label FROM parking_spots;",terms:["CASE","WHEN","ELSE"],example:"CASE WHEN daily_rate >= 1000 THEN 'дорогое' ELSE 'доступное' END",hints:["CASE проверяет условие для каждой строки.","Заверши выражение END и дай ему имя price_label."],minutes:5},
  {id:"spot-recursive-numbers",title:"Рекурсивная таблица чисел",prompt:"С помощью WITH RECURSIVE выведи числа от 1 до 10 в столбце n.",solution:"WITH RECURSIVE numbers(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM numbers WHERE n < 10) SELECT n FROM numbers;",terms:["WITH RECURSIVE","CTE","UNION ALL"],example:"WITH RECURSIVE numbers(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM numbers WHERE n < 10)",hints:["Начни CTE числом 1.","Рекурсивная часть прибавляет 1, пока n меньше 10."],minutes:7},
  {id:"spot-cheapest-place",title:"Самое дешёвое свободное место",prompt:"Найди номер самого дешёвого места и его тариф. Если тарифы одинаковые, выбери место с меньшим номером.",solution:"SELECT spot_number, daily_rate FROM parking_spots ORDER BY daily_rate, spot_number LIMIT 1;",terms:["ORDER BY","LIMIT"],example:"ORDER BY price ASC LIMIT 1",hints:["Сортируй сначала по цене, затем по номеру места.","LIMIT 1 оставит одну строку."],minutes:4,ordered:true},
  {id:"spot-view-expensive",title:"Представление дорогих мест",prompt:"Создай представление v_expensive_spots, которое показывает все парковочные места с ценой больше 2000 рублей.",solution:"CREATE VIEW v_expensive_spots AS SELECT * FROM parking_spots WHERE daily_rate > 2000;",terms:["CREATE VIEW","WHERE"],example:"CREATE VIEW view_name AS SELECT ...",hints:["Представление создаётся через CREATE VIEW ... AS.","В запросе отбери daily_rate > 2000."],minutes:6,mode:"state"},
  {id:"spot-view-zone-stats",title:"Сводка зон в представлении",prompt:"Создай v_zone_stats с зоной, количеством мест и числом мест без описания (missing_descriptions).",solution:"CREATE VIEW v_zone_stats AS SELECT zone, COUNT(*) AS spots_count, SUM(CASE WHEN description IS NULL THEN 1 ELSE 0 END) AS missing_descriptions FROM parking_spots GROUP BY zone;",terms:["CREATE VIEW","GROUP BY","CASE"],example:"CREATE VIEW view_name AS SELECT zone, COUNT(*) FROM parking_spots GROUP BY zone;",hints:["Сгруппируй места по зоне.","Число пропусков посчитай условной суммой CASE."],minutes:7,mode:"state"},
  {id:"spot-view-refresh",title:"Обнови представление цен",prompt:"Пересоздай v_expensive_spots так, чтобы оно показывало места дороже 2500 рублей. Используй DROP VIEW IF EXISTS и CREATE VIEW.",solution:"DROP VIEW IF EXISTS v_expensive_spots; CREATE VIEW v_expensive_spots AS SELECT * FROM parking_spots WHERE daily_rate > 2500;",terms:["DROP VIEW","CREATE VIEW"],example:"DROP VIEW IF EXISTS view_name; CREATE VIEW view_name AS SELECT ...;",hints:["Сначала удали старое представление.","Затем создай его снова с порогом 2500."],minutes:6,mode:"state"},
  {id:"spot-insert-vip",title:"Открой новую крытую зону",prompt:"Добавь три места VIP-C1, VIP-C2, VIP-C3 в новую зону «Крытая-2» по 2200 рублей в сутки. Для description укажи «Новая зона».",solution:"INSERT INTO parking_spots (id,spot_number,zone,daily_rate,description) VALUES (121,'VIP-C1','Крытая-2',2200,'Новая зона'),(122,'VIP-C2','Крытая-2',2200,'Новая зона'),(123,'VIP-C3','Крытая-2',2200,'Новая зона');",terms:["INSERT INTO","VALUES"],example:"INSERT INTO table_name (columns) VALUES (...), (...);",hints:["Один INSERT может добавить несколько строк.","Укажи значения для id, номера, зоны, тарифа и описания."],minutes:6,mode:"state"},
  {id:"spot-fill-empty-descriptions",title:"Заполни пустые описания",prompt:"Для мест без описания установи текст «Описание уточняется». Остальные описания не меняй.",solution:"UPDATE parking_spots SET description = 'Описание уточняется' WHERE description IS NULL;",terms:["UPDATE","SET","IS NULL"],example:"UPDATE parking_spots SET description = '...' WHERE description IS NULL;",hints:["Меняй только description.","Ограничь обновление условием IS NULL."],minutes:5,mode:"state"},
  {id:"spot-change-one-price",title:"Измени тариф одного места",prompt:"Для места VIP-01 установи цену 2100 рублей. Остальные места не меняй.",solution:"UPDATE parking_spots SET daily_rate = 2100 WHERE spot_number = 'VIP-01';",terms:["UPDATE","SET","WHERE"],example:"UPDATE parking_spots SET price = 100 WHERE item_id = 1;",hints:["Команда UPDATE меняет строки.","Условие WHERE должно выбрать только VIP-01."],minutes:5,mode:"state"},
  {id:"spot-price-check-trigger",title:"Запрети нулевую цену",prompt:"Создай триггер trg_spots_positive, который отменяет добавление места с нулевой или отрицательной ценой. Используй RAISE(ABORT, ...).",solution:"CREATE TRIGGER trg_spots_positive BEFORE INSERT ON parking_spots WHEN NEW.daily_rate <= 0 BEGIN SELECT RAISE(ABORT, 'Стоимость должна быть положительной'); END;",terms:["CREATE TRIGGER","BEFORE INSERT","RAISE"],example:"CREATE TRIGGER trigger_name BEFORE INSERT ON table_name WHEN NEW.price <= 0 BEGIN SELECT RAISE(ABORT, 'Некорректная цена'); END;",hints:["Проверяй NEW.daily_rate до вставки.","Для SQLite в триггере подходит SELECT RAISE(ABORT, ...)."],minutes:7,mode:"state"},
  {id:"spot-name-check-trigger",title:"Защити номер места от пустого значения",prompt:"Создай триггер trg_spot_number_required, который запрещает обновление, если новый spot_number пустой или состоит из пробелов.",solution:"CREATE TRIGGER trg_spot_number_required BEFORE UPDATE ON parking_spots WHEN length(trim(NEW.spot_number)) = 0 BEGIN SELECT RAISE(ABORT, 'Номер места обязателен'); END;",terms:["CREATE TRIGGER","BEFORE UPDATE","trim"],example:"WHEN length(trim(NEW.field_name)) = 0",hints:["Проверяй новое значение через NEW.spot_number.","trim удаляет пробелы по краям строки."],minutes:7,mode:"state"},
  {id:"spot-insert-log-trigger",title:"Веди журнал новых мест",prompt:"Создай таблицу spot_log и триггер trg_spot_insert_log. При добавлении места триггер должен записать его id и действие «insert».",solution:"CREATE TABLE spot_log (id INTEGER PRIMARY KEY AUTOINCREMENT, spot_id INTEGER NOT NULL, action TEXT NOT NULL, action_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TRIGGER trg_spot_insert_log AFTER INSERT ON parking_spots BEGIN INSERT INTO spot_log (spot_id, action) VALUES (NEW.id, 'insert'); END;",terms:["CREATE TABLE","CREATE TRIGGER","AFTER INSERT"],example:"CREATE TRIGGER log_insert AFTER INSERT ON table_name BEGIN INSERT INTO audit_log (...) VALUES (NEW.id, 'insert'); END;",hints:["Сначала создай таблицу журнала.","Триггер AFTER INSERT может добавить строку через NEW.id."],minutes:8,mode:"state"},
  {id:"spot-vip-repair",title:"Закрой место на ремонт",prompt:"Для VIP-01 временно поставь цену 0 и добавь к описанию пометку «на ремонте». Используй только SQLite-команды.",solution:"UPDATE parking_spots SET daily_rate = 0, description = COALESCE(description, '') || ' — на ремонте' WHERE spot_number = 'VIP-01';",terms:["UPDATE","COALESCE","||"],example:"description = COALESCE(description, '') || ' — отметка'",hints:["COALESCE заменит NULL пустой строкой.","Оператор || соединяет части текста в SQLite."],minutes:5,mode:"state"},
  {id:"spot-raise-standard-prices",title:"Подними тарифы стандартной зоны",prompt:"Увеличь цены всех мест в зоне «Стандарт» на 10 процентов одним UPDATE.",solution:"UPDATE parking_spots SET daily_rate = daily_rate * 1.1 WHERE zone = 'Стандарт';",terms:["UPDATE","SET","WHERE"],example:"SET price = price * 1.1",hints:["Новую цену вычисли из текущего daily_rate.","Ограничь изменение зоной Стандарт."],minutes:5,mode:"state"},
  {id:"spot-remove-one",title:"Удали выведенное место",prompt:"Место PEN-40 демонтировали. Удали только эту запись.",solution:"DELETE FROM parking_spots WHERE spot_number = 'PEN-40';",terms:["DELETE","WHERE"],example:"DELETE FROM parking_spots WHERE spot_number = 'A-01';",hints:["Используй DELETE FROM parking_spots.","Условие по spot_number не даст удалить остальные места."],minutes:5,mode:"state"},
  {id:"spot-remove-invalid-prices",title:"Очисти отрицательные тарифы",prompt:"Удалить из таблицы все строки со случайно отрицательным daily_rate.",solution:"DELETE FROM parking_spots WHERE daily_rate < 0;",terms:["DELETE","WHERE"],example:"DELETE FROM table_name WHERE price < 0;",hints:["Для удаления строк используется DELETE FROM.","Проверь отрицательную цену в условии WHERE."],minutes:5,mode:"state"},
  {id:"spot-price-rollback-pattern",title:"Безопасная транзакция изменения цен",prompt:"В транзакции верни тарифы зоны «Стандарт» к прежнему значению, разделив их на 1.1, и зафиксируй изменения через COMMIT.",solution:"BEGIN; UPDATE parking_spots SET daily_rate = daily_rate / 1.1 WHERE zone = 'Стандарт'; COMMIT;",terms:["BEGIN","UPDATE","COMMIT"],example:"BEGIN; UPDATE items SET price = price / 1.1; COMMIT;",hints:["BEGIN открывает транзакцию.","После UPDATE закончи её командой COMMIT."],minutes:6,mode:"state"},
  {id:"spot-add-price-index",title:"Ускорь поиск по зоне и цене",prompt:"Создай индекс idx_spots_zone_rate для столбцов zone и daily_rate таблицы parking_spots.",solution:"CREATE INDEX idx_spots_zone_rate ON parking_spots(zone, daily_rate);",terms:["CREATE INDEX","индекс"],example:"CREATE INDEX idx_name ON table_name(column_name);",hints:["Индекс создаётся командой CREATE INDEX.","Перечисли zone и daily_rate в скобках."],minutes:5,mode:"state"},
];

export const teacherExtraTasks: Task[] = exercises.map(exercise => ({
  ...exercise,
  module: "Работа 3 · Тарифы и места",
  minutes: exercise.minutes ?? 6,
  concept: exercise.concept ?? "Используй SQL, чтобы получить проверяемую сводку по реальным учебным тарифам парковки.",
  starter: "-- Напиши SQL-запрос по заданию",
  seed: exercise.seed ?? "",
  seedProfile: exercise.seedProfile ?? "parking-spots",
}));
