<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Classroom.Teacher</AssemblyName>
    <ApplicationIcon>../Classroom.Desktop/classroom.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Classroom.Desktop/Classroom.Desktop.csproj" />
  </ItemGroup>
</Project>
